name: Continuous Delivery
on:
  push:
    branches:
      - master

jobs:
  deploy_frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
        working-directory: ./frontend
      - run: npm install -g @angular/cli
        working-directory: ./frontend
      - run: ng build
        working-directory: ./frontend
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gsutil cp -r ./frontend/dist/magic-mirror/* gs://${{ secrets.GCP_BUCKET }}
      - run: gcloud compute url-maps invalidate-cdn-cache ${{ secrets.GCP_CDN_ORIGIN }} --path "/*"
  deploy_embedded:
    name: Deploy Balena Embedded
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Balena Deploy
        uses: bekriebel/balena-cli-action@v1
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy magic-mirror --source ./embedded --logs"