name: Continuous Delivery
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
        working-directory: ./frontend
      - run: npm install -g @angular/cli
        working-directory: ./frontend
      - run: ng build
        working-directory: ./frontend
      - run: ls
        working-directory: ./frontend/dist